name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./CopyCat/CopyCat.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore ./CopyCat/CopyCat.csproj

    - name: Locate test project
      id: locate-tests
      run: |
        echo "Locating test project file..."
        test_project=$(find . -name "CopyCat.Tests.csproj")
        echo "::set-output name=test_project::$test_project"

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal ${{ steps.locate-tests.outputs.test_project }}

    - name: Publish
      run: dotnet publish -c Release -o out ./CopyCat/CopyCat.csproj

    - name: Create CopyCat.exe
      run: |
        mkdir -p deployment
        cp out/CopyCat.exe deployment/CopyCat.exe

    - name: Deploy
      run: |
        # Add your deployment script here
        # For example, copy the output to a deployment directory
        xcopy deployment\* C:\path\to\deployment\directory /s /e /y
